using exs.notifications_model.Notifications;
using exs.notifications_model.Transports;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using Shouldly;
using Testcontainers.PostgreSql;

namespace exs.notifications_database.Tests
{
	/// <summary>
	/// Applies this repo's migrations to a real PostgreSQL instance and checks the schema they produce.
	///
	/// This is the only coverage the migrations have. Every other suite builds its schema from the model
	/// via EnsureCreated and never executes a migration, so a migration can be wrong in ways that still
	/// compile and still pass all of them - that is not hypothetical, an earlier hand-edit dropped two
	/// columns from fcm_sent (where NotificationQueueProcessor needs them) instead of fcm_queue and
	/// nothing went red. InitialFcmTransport is hand-edited by design, so it needs executing somewhere.
	///
	/// The context comes from NotificationDatabaseContextFactory rather than being built here, so the
	/// real design-time configuration - replaced SQL generator and model differ, and the
	/// __EFMigrationsHistory_Notifications history table - is what gets exercised.
	/// </summary>
	public sealed class MigrationTests : IAsyncLifetime
	{
		private readonly PostgreSqlContainer mPostgres = new PostgreSqlBuilder()
			.WithImage("postgres:16-alpine")
			.Build();

		private string? mPreviousConnectionStringVariable;

		/// <summary>
		/// The slice of the api-server's schema this repo's migrations depend on. InitialFcmTransport
		/// adds a column to notification and points a foreign key at it, but does not create it - that
		/// table belongs to server-side-base-api-server's migrations
		/// (main-database/Migrations/20260831152713_InitialCreate), and this repo only ever reads it.
		/// Standing it up by hand is what reproduces the real topology: a database where the api-server
		/// has already migrated and this repo's migrations run on top.
		/// </summary>
		private const string API_SERVER_PREREQUISITE_DDL = """
			CREATE TABLE notification (
			    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
			    "Date" timestamp with time zone NOT NULL,
			    "TypeId" smallint NOT NULL,
			    "EntityId" integer,
			    "Title" text,
			    "Body" text,
			    "Payload" text,
			    CONSTRAINT "PK_notification" PRIMARY KEY ("Id")
			);
			""";

		public async ValueTask InitializeAsync()
		{
			await mPostgres.StartAsync();

			// The factory reads this; setting it is how the test points the real design-time
			// configuration at the container instead of its non-routable placeholder.
			mPreviousConnectionStringVariable = Environment.GetEnvironmentVariable("ConnectionStrings__MainDatabase");
			Environment.SetEnvironmentVariable("ConnectionStrings__MainDatabase", mPostgres.GetConnectionString());

			await executeAsync(API_SERVER_PREREQUISITE_DDL);
		}

		public async ValueTask DisposeAsync()
		{
			Environment.SetEnvironmentVariable("ConnectionStrings__MainDatabase", mPreviousConnectionStringVariable);
			await mPostgres.DisposeAsync();
		}

		[Fact]
		public async Task Migrations_ApplyCleanlyOnTopOfTheApiServerSchema()
		{
			await using var context = createContext();

			await Should.NotThrowAsync(() => context.Database.MigrateAsync());

			var applied = await context.Database.GetAppliedMigrationsAsync();
			applied.ShouldContain(m => m.EndsWith("InitialFcmTransport"));
			applied.ShouldContain(m => m.EndsWith("AddNotificationPipelineIndexes"));
			(await context.Database.GetPendingMigrationsAsync()).ShouldBeEmpty();
		}

		[Fact]
		public async Task Migrations_RecordThemselvesInThisRepoOwnHistoryTable()
		{
			// Not the default __EFMigrationsHistory: this database is shared with the api-server's
			// MainDatabaseContext, and interleaving two repos' migration records in one table leaves
			// neither able to describe the database honestly.
			await using var context = createContext();
			await context.Database.MigrateAsync();

			var rows = await scalarsAsync("""SELECT "MigrationId" FROM "__EFMigrationsHistory_Notifications" ORDER BY 1""");

			rows.Count.ShouldBe(2);
			(await tableExistsAsync("__EFMigrationsHistory")).ShouldBeFalse();
		}

		[Fact]
		public async Task InitialMigration_BackfillsExistingNotificationsAsProcessedAndLeavesNoColumnDefault()
		{
			// The one piece of this that rewrites existing production data. Rows that predate the column
			// were handled by the old notification_queue pipeline, so they are Processed; defaulting them
			// to New would make the first sweep load the entire notification history and mass-expire it.
			await executeAsync("""
				INSERT INTO notification ("Date", "TypeId", "Title", "Body", "Payload")
				VALUES (now(), 1, 'pre-existing', 'body', '');
				""");
			await using var context = createContext();

			await context.Database.MigrateAsync();

			var statuses = await scalarsAsync("""SELECT "Status"::text FROM notification""");
			statuses.ShouldBe(["1"]); // Processed

			// The DEFAULT existed only to satisfy NOT NULL during the backfill. Left in place it would
			// silently mean "already Processed" for anything inserted outside EF - exactly backwards.
			var columnDefault = await scalarsAsync("""
				SELECT coalesce(column_default, '<none>') FROM information_schema.columns
				WHERE table_name = 'notification' AND column_name = 'Status'
				""");
			columnDefault.ShouldBe(["<none>"]);

			var nullable = await scalarsAsync("""
				SELECT is_nullable FROM information_schema.columns
				WHERE table_name = 'notification' AND column_name = 'Status'
				""");
			nullable.ShouldBe(["NO"]);
		}

		[Fact]
		public async Task InitialMigration_PutsUserSessionIdAndFcmTokenOnFcmSentAndNotOnFcmQueue()
		{
			// Direct regression guard for the hand-edit that went to the wrong table. fcm_sent needs both
			// (NotificationQueueProcessor writes them per send and the resume dedupe query reads them
			// back); on fcm_queue they were dead columns and were removed.
			await using var context = createContext();
			await context.Database.MigrateAsync();

			var sentColumns = await columnsOfAsync("fcm_sent");
			sentColumns.ShouldContain("UserSessionId");
			sentColumns.ShouldContain("FcmToken");

			var queueColumns = await columnsOfAsync("fcm_queue");
			queueColumns.ShouldNotContain("UserSessionId");
			queueColumns.ShouldNotContain("FcmToken");
		}

		[Fact]
		public async Task IndexMigration_CreatesThePollingIndexesAndKeepsTheNotificationOnePartial()
		{
			await using var context = createContext();
			await context.Database.MigrateAsync();

			var definitions = await scalarsAsync("""
				SELECT indexname || ' :: ' || indexdef FROM pg_indexes
				WHERE tablename IN ('notification', 'fcm_queue', 'fcm_sent') ORDER BY 1
				""");

			definitions.ShouldContain(d => d.StartsWith("IX_fcm_queue_Date :: "));
			definitions.ShouldContain(d => d.StartsWith("IX_fcm_sent_NotificationId_UserId :: "));

			// The partial filter is the whole point of this one - an unfiltered index on an append-only
			// log would grow with history while only ever being used to find the unprocessed backlog.
			var unprocessed = definitions.Single(d => d.StartsWith("IX_notification_unprocessed :: "));
			unprocessed.ShouldContain("WHERE");
			unprocessed.ShouldContain("""
				"Status" = 0
				""".Trim());
		}

		[Fact]
		public async Task MigratedSchema_MatchesTheModel_ForEveryEntityThisRepoOwns()
		{
			// The assertion that would have caught the wrong-table hand-edit on its own: EF generating
			// real SQL against the real schema. Any column the model expects and the migration did not
			// create (or vice versa) fails here rather than at runtime in production.
			await using var context = createContext();
			await context.Database.MigrateAsync();

			var notification = new Notification { Date = DateTime.UtcNow, TypeId = 3, EntityId = 42, Title = "t", Body = "b", Payload = "{}" };
			context.Add(notification);
			await context.SaveChangesAsync();

			context.Add(new FcmQueue { Date = DateTime.UtcNow, NotificationId = notification.Id, UserId = 7, IsProcessing = true });
			context.Add(new FcmSent { Date = DateTime.UtcNow, NotificationId = notification.Id, UserId = 7, UserSessionId = 11, FcmToken = "token", Error = null });
			await context.SaveChangesAsync();

			(await context.Set<Notification>().SingleAsync(n => n.Id == notification.Id)).Status.ShouldBe(NotificationStatus.New);
			(await context.Set<FcmQueue>().SingleAsync()).IsProcessing.ShouldBeTrue();

			// Exactly the shape of NotificationQueueProcessor's resume dedupe query, which is what breaks
			// if fcm_sent loses UserSessionId or FcmToken.
			var alreadyDelivered = await context.Set<FcmSent>()
				.Where(e => e.NotificationId == notification.Id && e.UserId == 7 && e.UserSessionId != null && e.FcmToken != null && e.Error == null)
				.Select(e => e.UserSessionId)
				.ToListAsync();
			alreadyDelivered.ShouldBe([11]);
		}

		private static NotificationDatabaseContext createContext() =>
			new NotificationDatabaseContextFactory().CreateDbContext([]);

		private async Task<List<string>> columnsOfAsync(string table) =>
			await scalarsAsync($"SELECT column_name FROM information_schema.columns WHERE table_name = '{table}' ORDER BY 1");

		private async Task<bool> tableExistsAsync(string table) =>
			(await scalarsAsync($"SELECT to_regclass('public.\"{table}\"')::text")).Single() != "<null>";

		private async Task executeAsync(string sql)
		{
			await using var connection = new NpgsqlConnection(mPostgres.GetConnectionString());
			await connection.OpenAsync();
			await using var command = new NpgsqlCommand(sql, connection);
			await command.ExecuteNonQueryAsync();
		}

		private async Task<List<string>> scalarsAsync(string sql)
		{
			await using var connection = new NpgsqlConnection(mPostgres.GetConnectionString());
			await connection.OpenAsync();
			await using var command = new NpgsqlCommand(sql, connection);
			await using var reader = await command.ExecuteReaderAsync();

			var results = new List<string>();
			while (await reader.ReadAsync())
			{
				results.Add(reader.IsDBNull(0) ? "<null>" : reader.GetString(0));
			}
			return results;
		}
	}
}
