using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace exs.notifications_database.Migrations
{
    /// <summary>
    /// Bootstrap migration for this repo.
    ///
    /// It can provision a fresh database by creating the shared notification/session tables and the
    /// notification transport tables in one pass, but it also remains safe to apply to a database
    /// where the shared schema already exists: the DDL is conditional and only fills in what is
    /// missing.
    ///
    /// Keep the column names in sync with NotificationsModelBuilder and the model snapshot; the
    /// worker relies on the exact PostgreSQL names that EF would generate for these entity shapes.
    /// </summary>
    public partial class InitialFcmTransport : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS "client_device_platform" (
    "Id" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "LatestUpdate" timestamp with time zone NOT NULL DEFAULT now(),
    "Name" text NOT NULL,
    "PlatformKeys" text NOT NULL,
    CONSTRAINT "PK_client_device_platform" PRIMARY KEY ("Id")
);
""");

            migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS "user_session" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "LatestUpdate" timestamp with time zone NOT NULL DEFAULT now(),
    "MobileGpsDeviceId" integer NULL,
    "SessionSourceId" smallint NOT NULL,
    "StatusId" smallint NOT NULL,
    "UserId" integer NOT NULL,
    "ClientInfo_AppUID" text NOT NULL,
    "ClientInfo_AppVersion" text NOT NULL,
    "ClientInfo_CodeVersion" text NOT NULL,
    "ClientInfo_DeviceUID" text NOT NULL,
    "ClientInfo_FCM_FID" text NOT NULL,
    "ClientInfo_PlatformId" smallint NOT NULL,
    "Token_CreationTime" timestamp with time zone NOT NULL,
    "Token_ExpirationTime" timestamp with time zone NOT NULL,
    "Token_LatestRefreshTime" timestamp with time zone NOT NULL,
    "Token_PreviousSessionRotationKey" text NOT NULL,
    "Token_SessionRotationKey" text NOT NULL,
    CONSTRAINT "PK_user_session" PRIMARY KEY ("Id")
);
""");

            migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS "notification_type" (
    "Id" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "LatestUpdate" timestamp with time zone NOT NULL DEFAULT now(),
    "Name" text NOT NULL,
    CONSTRAINT "PK_notification_type" PRIMARY KEY ("Id")
);
""");

            migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS "notification" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Body" text NULL,
    "Date" timestamp with time zone NOT NULL,
    "EntityId" integer NULL,
    "Payload" text NULL,
    "Status" smallint NOT NULL,
    "Title" text NULL,
    "TypeId" smallint NOT NULL,
    CONSTRAINT "PK_notification" PRIMARY KEY ("Id")
);
""");

            migrationBuilder.Sql("""
ALTER TABLE IF EXISTS "notification"
    ADD COLUMN IF NOT EXISTS "Status" smallint NOT NULL DEFAULT 1;
""");

            migrationBuilder.Sql("""
ALTER TABLE IF EXISTS "notification"
    ALTER COLUMN "Status" DROP DEFAULT;
""");

            migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS "notification2user" (
    "UserId" integer NOT NULL,
    "NotificationId" integer NOT NULL,
    CONSTRAINT "PK_notification2user" PRIMARY KEY ("UserId", "NotificationId"),
    CONSTRAINT "FK_notification2user_notification_NotificationId" FOREIGN KEY ("NotificationId") REFERENCES "notification" ("Id") ON DELETE CASCADE
);
""");

            migrationBuilder.Sql("""
CREATE INDEX IF NOT EXISTS "IX_notification2user_NotificationId"
    ON "notification2user" ("NotificationId");
""");

            migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS "fcm_sent" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "NotificationId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "UserSessionId" integer NULL,
    "FcmToken" text NULL,
    "Error" text NULL,
    CONSTRAINT "PK_fcm_sent" PRIMARY KEY ("Id")
);
""");

            migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS "fcm_queue" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "NotificationId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "IsProcessing" boolean NOT NULL,
    CONSTRAINT "PK_fcm_queue" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_fcm_queue_notification_NotificationId" FOREIGN KEY ("NotificationId") REFERENCES "notification" ("Id") ON DELETE CASCADE
);
""");

            migrationBuilder.Sql("""
CREATE INDEX IF NOT EXISTS "IX_fcm_queue_NotificationId"
    ON "fcm_queue" ("NotificationId");
""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Intentionally empty, and not an oversight: NoDropMigrationsModelDiffer strips every
            // DropTable/DropColumn operation out of the diff in both directions, so the scaffolder had
            // nothing to emit here. Rolling this migration back is a deliberate manual DDL exercise -
            // the estate's rule is that data under a retired table or column outlives the model.
        }
    }
}
