// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using exs.notifications_database;

#nullable disable

namespace exs.notifications_database.Migrations
{
    [DbContext(typeof(NotificationDatabaseContext))]
    partial class NotificationDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("exs.modelCommons.AppStructure.ClientDevicePlatform", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("LatestUpdate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlatformKeys")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("client_device_platform", (string)null);
                });

            modelBuilder.Entity("exs.modelCommons.UserManagement.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LatestUpdate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("MobileGpsDeviceId")
                        .HasColumnType("integer");

                    b.Property<short>("SessionSourceId")
                        .HasColumnType("smallint");

                    b.Property<short>("StatusId")
                        .HasColumnType("smallint");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ClientInfo", "exs.modelCommons.UserManagement.UserSession.ClientInfo#SessionClientInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AppUID")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("AppVersion")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CodeVersion")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("DeviceUID")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("FCM_FID")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<short>("PlatformId")
                                .HasColumnType("smallint");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token", "exs.modelCommons.UserManagement.UserSession.Token#SessionTokenInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("CreationTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("ExpirationTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("LatestRefreshTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("PreviousSessionRotationKey")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("SessionRotationKey")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.ToTable("user_session", (string)null);
                });

            modelBuilder.Entity("exs.notifications_model.Notifications.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<short>("TypeId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_notification_unprocessed")
                        .HasFilter("\"Status\" = 0");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("exs.notifications_model.Notifications.NotificationToUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("NotificationId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "NotificationId");

                    b.HasIndex("NotificationId");

                    b.ToTable("notification2user", (string)null);
                });

            modelBuilder.Entity("exs.notifications_model.Notifications.NotificationType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("LatestUpdate")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("notification_type", (string)null);
                });

            modelBuilder.Entity("exs.notifications_model.Transports.FcmQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsProcessing")
                        .HasColumnType("boolean");

                    b.Property<int>("NotificationId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_fcm_queue_Date");

                    b.HasIndex("NotificationId");

                    b.ToTable("fcm_queue", (string)null);
                });

            modelBuilder.Entity("exs.notifications_model.Transports.FcmSent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("FcmToken")
                        .HasColumnType("text");

                    b.Property<int>("NotificationId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserSessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId", "UserId")
                        .HasDatabaseName("IX_fcm_sent_NotificationId_UserId");

                    b.ToTable("fcm_sent", (string)null);
                });

            modelBuilder.Entity("exs.notifications_model.Notifications.NotificationToUser", b =>
                {
                    b.HasOne("exs.notifications_model.Notifications.Notification", "Notification")
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("exs.notifications_model.Transports.FcmQueue", b =>
                {
                    b.HasOne("exs.notifications_model.Notifications.Notification", "Notification")
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });
#pragma warning restore 612, 618
        }
    }
}
