<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>exs.notifications_database</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\server-side-commons\exs.dbContextCommons\exs.dbContextCommons.csproj" />
    <ProjectReference Include="..\exs.notifications-model\exs.notifications-model.csproj" />
  </ItemGroup>

</Project>
